package cn.shadow.archetype.dao;

import cn.shadow.archetype.entity.Group;
import java.util.List;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    List<Group> selectAll();
}