package cn.shadow.archetype.dao;

import cn.shadow.archetype.entity.Role;
import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    List<Role> selectAll();
}