package cn.shadow.archetype.dao;

import cn.shadow.archetype.entity.RoleGroup;
import java.util.List;

public interface RoleGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_group
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    int insert(RoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_group
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    List<RoleGroup> selectAll();
}