package cn.shadow.archetype.dao;

import cn.shadow.archetype.entity.RoleModule;
import java.util.List;

public interface RoleModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    int insert(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_module
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    List<RoleModule> selectAll();
}