package cn.shadow.archetype.dao;

import cn.shadow.archetype.entity.Teller;
import java.util.List;
import java.util.Map;

public interface TellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teller
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teller
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    int insert(Teller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teller
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    Teller selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teller
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    List<Teller> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teller
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    int updateByPrimaryKey(Teller record);
    /**
     * 这个方法是我自己写的
     * 用于查看该用户所有的可用的借口
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    List<String> TellerPower(Map map);
}