package cn.shadow.archetype.entity;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.fk_province_id
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    private Integer fkProvinceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.fk_province_id
     *
     * @return the value of city.fk_province_id
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    public Integer getFkProvinceId() {
        return fkProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.fk_province_id
     *
     * @param fkProvinceId the value for city.fk_province_id
     *
     * @mbg.generated Mon Sep 09 22:28:58 CST 2019
     */
    public void setFkProvinceId(Integer fkProvinceId) {
        this.fkProvinceId = fkProvinceId;
    }
}