package cn.shadow.archetype.entity;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.remark
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.groupname
     *
     * @return the value of group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.groupname
     *
     * @param groupname the value for group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.remark
     *
     * @return the value of group.remark
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.remark
     *
     * @param remark the value for group.remark
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}