package cn.shadow.archetype.entity;

public class RoleModule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module.module
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module.role
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module.module
     *
     * @return the value of role_module.module
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module.module
     *
     * @param module the value for role_module.module
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module.role
     *
     * @return the value of role_module.role
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module.role
     *
     * @param role the value for role_module.role
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}