package cn.shadow.archetype.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolename
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.remark
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.group
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String group;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolename
     *
     * @return the value of role.rolename
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolename
     *
     * @param rolename the value for role.rolename
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.remark
     *
     * @return the value of role.remark
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.remark
     *
     * @param remark the value for role.remark
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.group
     *
     * @return the value of role.group
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.group
     *
     * @param group the value for role.group
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }
}