package cn.shadow.archetype.entity;

public class RoleGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_group.rolename
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String groupname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_group.rolename
     *
     * @return the value of role_group.rolename
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_group.rolename
     *
     * @param rolename the value for role_group.rolename
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_group.groupname
     *
     * @return the value of role_group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_group.groupname
     *
     * @param groupname the value for role_group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }
}