package cn.shadow.archetype.entity;

public class Teller {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teller.id
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teller.password
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teller.phone
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teller.id
     *
     * @return the value of teller.id
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teller.id
     *
     * @param id the value for teller.id
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teller.password
     *
     * @return the value of teller.password
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teller.password
     *
     * @param password the value for teller.password
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teller.phone
     *
     * @return the value of teller.phone
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teller.phone
     *
     * @param phone the value for teller.phone
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}