package cn.shadow.archetype.entity;

public class TellerGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teller_group.teller_id
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private Integer tellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teller_group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    private String groupname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teller_group.teller_id
     *
     * @return the value of teller_group.teller_id
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public Integer getTellerId() {
        return tellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teller_group.teller_id
     *
     * @param tellerId the value for teller_group.teller_id
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setTellerId(Integer tellerId) {
        this.tellerId = tellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teller_group.groupname
     *
     * @return the value of teller_group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teller_group.groupname
     *
     * @param groupname the value for teller_group.groupname
     *
     * @mbg.generated Thu Sep 19 21:48:05 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }
}